esphome:
  name: aireacondicionado-esp12f
  platform: ESP8266
  board: nodemcuv2

external_components:
  - source:
      type: local
      path: custom_components

# Example configuration entry

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 100%

climate:
  - platform: electrolux_climate
    name: "aire acondicionado"

#esp32:
#  board: nodemcu-32s
#  framework:
#    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret "wifi-ssid"
  password: !secret "wifi-pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret "ap-ssid"
    password: !secret "ap-pass"

captive_portal:
